In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('PlayTennis.csv')
df

     Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No

In [3]:
df.isnull().sum()

Outlook        0
Temperature    0
Humidity       0
Wind           0
Play Tennis    0
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Outlook_le = le.fit_transform(df.Outlook)
Temperature_le = le.fit_transform(df.Temperature)
Humidity_le = le.fit_transform(df.Humidity)
Wind_le = le.fit_transform(df.Wind)
Play Tennis_le = le.fit_transform(df.Play Tennis)

df["Outlook_le"] = Outlook_le
df["Temperature_le"] = Temperature_le
df["Humidity_le"] = Humidity_le
df["Wind_le"] = Wind_le
df["Play_le"] = Play_le

SyntaxError: invalid syntax (1653976465.py, line 7)